version: '3'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    hostname: nextcloud
    restart: always
    #ports:
    #  - "8080:80"
    volumes:
      - ./nextcloud-data:/var/www/html
    networks:
      - ecosystem
    environment:
      - NEXTCLOUD_ADMIN_USER=nextadmin
      - NEXTCLOUD_ADMIN_PASSWORD=nextadmin

networks:
  ecosystem:
    external: true  # 既に作成されたネットワークを使用する場合