version: '3'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    hostname: nextcloud
    restart: always
    #ports:
    #  - "8080:80"
    volumes:
      - ./nextcloud-data:/var/www/html
    networks:
      ecosystem:
        ipv4_address: 172.10.10.4  # 指定したIPアドレスを追加
    environment:
      - NEXTCLOUD_ADMIN_USER=nextadmin
      - NEXTCLOUD_ADMIN_PASSWORD=nextadmin
      # proxyコンテナのIPアドレス
      - TRUSTED_PROXIES=172.10.10.3

networks:
  ecosystem:
    external: true  # 既に作成されたネットワークを使用する場合