version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    networks:
      ecosystem:
        ipv4_address: 172.10.10.3  # 指定したIPアドレスを追加
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # カスタム設定を使用する場合
      # - ./conf.d:/etc/nginx/conf.d:ro  # カスタム設定を使用する場合
      # - ./html:/usr/share/nginx/html  # 静的なHTMLファイルを提供する場合
      - ./ssl/certs:/etc/ssl/certs  # SSL証明書をホストからコンテナにマウント
      - ./ssl/private:/etc/ssl/private  # 秘密鍵をホストからコンテナにマウント
      - nextcloud_data:/usr/share/nginx/html # Nextcloudとのデータ共有用

networks:
  ecosystem:
    external: true  # 既に作成されたネットワークを使用する場合

volumes:
  nextcloud_data:
